### ISSUE TITLE
tts doesn't work 

### ISSUE THREAD

**Issue by rapon233** [jing332/tts-server-android#135]
之前在阅读app中正常调用TTS功能，今天发现不能用，在软件中测试，试听功能无法使用，错误代码如下：
app 202307261647稳定版
OS: one UI 6.0 android 14

`go.Universe$proxyerror: dial tcp: lookup speech.platform.bing.com: No address associated with hostname
	at tts_server_lib.EdgeApi.getEdgeAudio(Native Method)
	at com.github.jing332.tts_server_android.model.speech.tts.h.getAudio(MsTTS.kt:385)
	at com.github.jing332.tts_server_android.model.speech.tts.e.getAudioWithSystemParams(ITextToSpeechEngine.kt:23)
	at com.github.jing332.tts_server_android.model.speech.tts.e.getAudioWithSystemParams$default(ITextToSpeechEngine.kt:14)
	at u5.w0$i$b.invokeSuspend(SysTtsListItemHelper.kt:45)
	at cc.a.resumeWith(ContinuationImpl.kt:9)
	at tc.j0.run(DispatchedTask.kt:112)
	at yc.h$a.run(LimitedDispatcher.kt:4)
	at ad.k.run(Tasks.kt:3)
	at ad.a$a.run(CoroutineScheduler.kt:96)
`

**Comment by jing332** [comment]
@rapon233 无法解析域名，是设备的网络问题，可能和dns有关
