### ISSUE TITLE
Android 14 permissions error

### ISSUE THREAD

**Issue by mablue** [jing332/tts-server-android#161]
https://bin.kv2.dev/~65c67b205de7ed6bfdbd44ec

I use TalkBack but it say you will append a new tts with {read all } rule

Thats my config
https://jt12.de/SYV2_4/2024/02/10/3/24/39/170750667965c67bf7c9f55.json

**Comment by mablue** [comment]
https://bin.kv2.dev/~65c67c6c5de7ed6bfdbd44fb

```
2024-02-09T22:56:33.229
版本代码：973， 版本名称：1.24.020413
崩溃详情：
java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{faa5cd1 21152:com.github.jing332.tts_server_android/u0a449} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6825)
	at android.app.Service.startForeground(Service.java:775)
	at com.github.jing332.tts_server_android.service.systts.SystemTtsService$j.invoke(SystemTtsService.kt:42)
	at a2.u.run(R8$$SyntheticClass:15)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8244)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

```
2024-02-09T22:56:29.681
版本代码：973， 版本名称：1.24.020413
崩溃详情：
java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{ef60d87 21062:com.github.jing332.tts_server_android/u0a449} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3045)
	at android.os.Parcel.readException(Parcel.java:3028)
	at android.os.Parcel.readException(Parcel.java:2970)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6825)
	at android.app.Service.startForeground(Service.java:775)
	at com.github.jing332.tts_server_android.service.systts.SystemTtsService.onSynthesizeText(SystemTtsService.kt:226)
	at android.speech.tts.TextToSpeechService$SynthesisSpeechItem.playImpl(TextToSpeechService.java:1033)
	at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
	at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2670)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2360)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1688)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13383)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3418)

```
