### ISSUE TITLE
Samsung a23 phone error on import config

### ISSUE THREAD

**Issue by mablue** [jing332/tts-server-android#166]
1) Internal explorer is empty.[premently not usable on other phones too]
2) System file explorer gives that:
```
java.lang.SecurityException: com.samsung.android.providers.media has no access to content://media/external_primary/file/1000010271
,  at 
android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
,  at android.os.Parcel.createException(Parcel.java:3053)
,  at android.os.Parcel.readException(Parcel.java:3036)
,  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
,  at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
,  at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:814)
,  at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2043)
,  at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1858)
,  at android.content.ContentResolver.openInputStream(ContentResolver.java:1528)
,  at cb.d.g(FileUtils.kt:39)
,  at j9.r.invokeSuspend(RestoreDialog.kt:59)
,  at ff.a.resumeWith(ContinuationImpl.kt:9)
,  at eg.p0.run(DispatchedTask.kt:111)
,  at a2.l1.U(AndroidUiDispatcher.android.kt:7)
,  at a2.l1$c.run(AndroidUiDispatcher.android.kt:3)
,  at android.os.Handler.handleCallback(Handler.java:958)
,  at android.os.Handler.dispatchMessage(Handler.java:99)
,  at android.os.Looper.loopOnce(Looper.java:230)
,  at android.os.Looper.loop(Looper.java:319)
,  at android.app.ActivityThread.main(ActivityThread.java:8893)
,  at java.lang.reflect.Method.invoke(Native Method)
,  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
,  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
,com.samsung.android.providers.media

```

**Comment by mablue** [comment]
[ttsrv-backup-multi-espeak.zip](https://github.com/jing332/tts-server-android/files/14296822/ttsrv-backup-multi-espeak.zip)
[ttsrv-backup-multi-shepra&google.zip](https://github.com/jing332/tts-server-android/files/14296823/ttsrv-backup-multi-shepra.google.zip)
[ttsrv-backup-MultiLanguageRules.zip](https://github.com/jing332/tts-server-android/files/14296824/ttsrv-backup-MultiLanguageRules.zip)
[ttsrv-speechRules-multiVoice.json](https://github.com/jing332/tts-server-android/files/14296825/ttsrv-speechRules-multiVoice.json)
