### ISSUE TITLE
英文文章无法正确发送英文句子

### ISSUE THREAD

**Issue by Downupanddownup** [jing332/tts-server-android#178]
在结合阅读APP和GPT-Sovits的第三方推理包进行TTS时，发现中文文章能够正常推送至后台，但是纯英文文章的句子会直接跳过，后台未接收到英文文本，不知道是阅读APP的问题，还是TTS Service的问题

**Comment by vincediangu** [comment]
我这边也是同样情况，中英文混读的英文有时能读出来，但是发音很怪异。试听英文的发音会显示如下信息：
java.lang.NullPointerException: Attempt to get length of null array at
java.io.ByteArrayInputStream.<init>(ByteArraylnp utStream.java:108) at
com.github.jing332.tts_server_android.model.sp eech.tts.h.getAudio(MsTTS.kt:322) at
com.github.jing332.tts_server_android.model.sp eech.tts.e.getAudioWithSystemParams(ITextToS peechEngine.kt:23) at
com.github.jing332.tts_server_android.model.sp eech.tts.e.getAudioWithSystemParams$default(1 TextToSpeechEngine.kt:14) at
q9.a$a$a.invokeSuspend(AuditionDialog.kt:132) at ff.a.resumeWith(Continuationlmpl.kt:9) at eg.p0.run(DispatchedTask.kt:111) at jg.j$a.run(LimitedDispatcher.kt:4) at lg.i.run(Tasks.kt:3)
at lg.a$a.run(CoroutineScheduler.kt:96)
