### ISSUE TITLE
将flac格式的音乐添加到BGM时出错

### ISSUE THREAD

**Issue by wangyi1573** [jing332/tts-server-android#199]
java.lang.NumberFormatException: For input string: "msf:1000014591"
	at java.lang.Long.parseLong(Long.java:751)
	at java.lang.Long.valueOf(Long.java:1203)
	at l5.a.b(ASFUriUtils.kt:104)
	at l5.a.c(ASFUriUtils.kt:48)
	at C4.a$i.invoke(BgmTtsUI.kt:24)
	at L6.o.a(R8$$SyntheticClass:11)
	at f.d.a(ActivityResultRegistry.kt:49)
	at c.h.onActivityResult(ComponentActivity.kt:3)
	at Q1.j.onActivityResult(FragmentActivity.java:6)
	at android.app.Activity.dispatchActivityResult(Activity.java:9278)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5743)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5794)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:70)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2600)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8602)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)

**Comment by sht2017** [comment]
应该是权限问题 可以试试看换个目录（不应该是系统创建的Downloads什么的）
