### ISSUE TITLE
在主页上的新增的测试按钮发现一个很严重的问题，调都变了已启用, 云希（zh-CN-YunxiNeural）, 目标对话，接口Azure，属性：无-无 | 强度:1.0
语速:跟随 | 音量:50 | 音高:跟随，格式：audio-48khz-96kbitrate-mono-mp3类似的这种参数的所有语音都出现过问题

### ISSUE THREAD

**Issue by zmyznu** [jing332/tts-server-android#53]
如题https://user-images.githubusercontent.com/121068584/217189131-3686d34e-6199-4042-87c0-8e47d2ffcde3.mp4

**Comment by zmyznu** [comment]
发现使用本地TTS再点击主页上的那个测试按钮，发现一个很严重的问题，就是说你测试完一次，他给你播放了本地TTS的输出，那么你要测试第2次，要不就是加载中，要不就是如下的报错。java.lang.NullPointerException: voices must not be null
	at b4.i.N(SourceFile:22)
	at b4.i$g$a.p(SourceFile:40)
	at ca.a.h(Unknown Source:8)
	at sa.i0.run(Unknown Source:100)
	at sa.o0.m0(SourceFile:154)
	at a2.a.G(SourceFile:61)
	at b4.i.O(SourceFile:90)
	at b4.i.c(SourceFile:6)
	at q4.e0$b.p(SourceFile:19)
	at ca.a.h(Unknown Source:8)
	at sa.i0.run(Unknown Source:100)
	at kotlinx.coroutines.internal.f.run(Unknown Source:11)
	at kotlinx.coroutines.scheduling.j.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a$a.run(SourceFile:79)

**Comment by jing332** [comment]
数值跟随系统的问题，获取不到系统值，音高就变成了-100

**Comment by zmyznu** [comment]
那好吧，谢谢开发者

**Comment by jing332** [comment]
目前临时解决，把语速设为50，音高设为0
