### ISSUE TITLE
新版本里背景音乐不能播放

### ISSUE THREAD

**Issue by sandage125** [jing332/tts-server-android#75]
选取音乐时可以点击播放，但选中到APP中就不能试听播放了
java.lang.Exception: 请在编辑界面中点击音乐路径进行测试播放
	at com.github.jing332.tts_server_android.model.speech.tts.c.getAudio(BgmTTS.kt:5)
	at com.github.jing332.tts_server_android.model.speech.tts.f.getAudioWithSystemParams(ITextToSpeechEngine.kt:23)
	at com.github.jing332.tts_server_android.model.speech.tts.f.getAudioWithSystemParams$default(ITextToSpeechEngine.kt:14)
	at g5.i0$i$b.invokeSuspend(SysTtsListItemHelper.kt:45)
	at va.a.resumeWith(ContinuationImpl.kt:9)
	at lb.h0.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.f.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.j.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.a$a.run(CoroutineScheduler.kt:79)

**Comment by jing332** [comment]
`请在编辑界面中点击音乐路径进行测试播放`
